# Generated by Django 3.0.3 on 2020-03-04 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_remove_tag_trail_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
