# Generated by Django 3.0.3 on 2020-03-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0004_auto_20200304_2153'),
        ('user', '0002_auto_20200228_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorites',
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(to='trail.Trail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
