# Generated by Django 3.0.3 on 2020-03-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0004_auto_20200304_2153'),
        ('user', '0004_auto_20200304_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='trail.Trail'),
        ),
    ]
