# Generated by Django 3.0.3 on 2020-03-05 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200304_0512'),
        ('user', '0004_auto_20200304_2157'),
    ]

    operations = [
    ]
