# Generated by Django 3.0.3 on 2020-03-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_merge_20200305_2115'),
        ('user', '0005_auto_20200305_1913'),
    ]

    operations = [
    ]
