# Generated by Django 3.0.3 on 2020-03-03 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_remove_tag_trail_id'),
        ('trail', '0002_auto_20200302_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tag.Tag'),
        ),
    ]
