# Generated by Django 3.0.3 on 2020-03-04 21:53

from django.db import migrations, models
import trail.models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_remove_tag_slug'),
        ('trail', '0003_trail_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='tag',
        ),
        migrations.AddField(
            model_name='trail',
            name='tags',
            field=models.ManyToManyField(to='tag.Tag'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=trail.models.upload_image_path),
        ),
    ]
